version: '3.2'

services:
    rtsp-server:
        image: rtsp-server
        hostname: rtsp-server
        container_name: rtsp-server
        ports: 
            - 8554:8554
        environment: 
            - INPUT=/tmp/Atak/videos/ch0002_00000001475000000.mp4
            - DATE=12/02/2019
            - JUMP_TO=20:46:20
            - BEGIN_TIME=20:17:30
        build:
            context: .
        volumes:
            - c:\:/tmp            

