version: '3.2'

services:
    rtsp-server:
        image: rtsp-server
        hostname: rtsp-server
        container_name: rtsp-server
        ports: 
            - 8554:8554
        environment: 
            - INPUT=/tmp/Atak/videos/videoBahia.mp4
            - DATE=12/02/2019
            - JUMP_TO=00:19:55
            - BEGIN_TIME=00:00:00
        build:
            context: .
        volumes:
            - c:\:/tmp            

